### PR TITLE
rg-200: Landing page BR-19

### PR DESCRIPTION
**Pull request by honkster-nazarii**
Added navigation to landing page buttons

### CODE REVIEW

**Comment by honkster-nazarii** [comment]
[Landing page BR-19](https://trello.com/c/O2yr7YLP/200-landing-page-br-19)

**Comment by siefimov** [comment]
It is written in the task that "Expected result: Upon clicking the [Get Started] and [Create resume for free] buttons, the user should be redirected to the sign-up page.". But in fact, click redirectd to log-in page. Is it agreed?

**Comment by siefimov** [comment]
Clicking this button doesn't redirect to the sign-up page.
image

**Review by siefimov — CHANGES_REQUESTED** [review]
Please, check my comments

**Review by MaxPoplavskiy — APPROVED** [review]

**Review by RevolveStrm — APPROVED** [review]

**Review by siefimov — APPROVED** [review]

**Pull request merged**
