### PR TITLE
rg-157: Fix password hint

### PR DESCRIPTION
**Pull request by vlad-blip**

### CODE REVIEW

**Comment by vlad-blip** [comment]
[Registration page BR-13](https://trello.com/c/MESHnx3e/157-registration-page-br-13)

**Review by MaxPoplavskiy — APPROVED** [review]

**Comment by ValentinaTenus** [comment]
I've fixed it in https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-resumegemm/pull/118
doesn't matter which changes will be accepted it looks the same

**Review by ValentinaTenus — APPROVED** [review]

**Review by Icerock10 — APPROVED** [review]

**Comment by Icerock10** [comment]
conflicts

**Comment by vlad-blip** [comment]
Looks like the problem was solved and merged already.

**Pull request closed without merging**
